###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ariel",
    "apellido": "Sutomusu",
    "curso": 8
}
###
DELETE http://localhost:9000/api/9 HTTP/1.1
###
PUT http://localhost:9000/api/3 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pau",
    "apellido": "Cubars'i",
    "curso": 1

}